### ISSUE TITLE
error: use of undeclared identifier 'REST_Geant4_ViewEvent'

### ISSUE THREAD

**Issue by tsiledak** [rest-for-physics/restG4#116]
Dear experts,

I have just downloaded and installed  official/v2.4.0 restG4
(~/rest-framework/build$ cmake -DCMAKE_INSTALL_PREFIX=../install -DREST_ALL_LIBS=ON -DREST_G4=ON ..).
I used geant4 and root executing the appropriate scripts from scripts/installation folder.
I am able to run the example 08 but when I am trying to visualize the events as is stated
in https://github.com/rest-for-physics/restG4/blob/master/examples/08.Alphas/README.md I am getting an error concerning the 'REST_Geant4_ViewEvent'.
Any idea why?

Thanks a lot in advance

Best regards

Georgios

================================

restRoot
= Loading libraries ...
 - /home/gt226504/rest-framework/install/lib/libRestFramework.so
 - /home/gt226504/rest-framework/install/lib/libRestAxion.so
 - /home/gt226504/rest-framework/install/lib/libRestDetector.so
 - /home/gt226504/rest-framework/install/lib/libRestTrack.so
 - /home/gt226504/rest-framework/install/lib/libRestWimp.so
 - /home/gt226504/rest-framework/install/lib/libRestGeant4.so
 - /home/gt226504/rest-framework/install/lib/libRestLegacy.so
 - /home/gt226504/rest-framework/install/lib/libRestConnectors.so
 - /home/gt226504/rest-framework/install/lib/libRestRaw.so

root [0] REST_Geant4_ViewEvent("data/Run_5MeV_1um.root")
input_line_195:2:3: error: use of undeclared identifier 'REST_Geant4_ViewEvent'
 (REST_Geant4_ViewEvent("data/Run_5MeV_1um.root"))
  ^
Error in <HandleInterpreterException>: Error evaluating expression (REST_Geant4_ViewEvent("data/Run_5MeV_1um.root"))
Execution of your code was aborted.
root [1]

**Comment by jgalan** [comment]
Hi Giorgos, you need to execute `restRoot` with macros. This is done executing `restRootMacros` or `restRoot -m`. The reason is that loading all macros is time consuming, and we don't want to always use macros.

On top of that, there is an alternative way of launching macros, using `restManager`:

```
restManager  Geant4_ViewEvent data/Run_5MeV_1um.root
```

Perhaps we should write that somewhere in the documentation, in which spot of the documentation you were having a look so that we can update accordingly?

Cheers!

**Comment by lobis** [comment]
Hello @tsiledak,

The current event visualization uses a ROOT macro `REST_Geant4_ViewEvent.C` that should be present in `$REST_PATH/macros/geant4`. This macro should be accessible from `restRoot` but you need to invoke it with the `restRoot -m` flag in order to load macros.

In order to visualize events I prefer to use `restGeant4_ViewEvent simulation.root` directly from the shell (bash, not root).

**Comment by tsiledak** [comment]
Thanks so much for the quick reply and solution!
It is my fault not to see carefully that restRootMacros is the appropriate command to execute.
